### ISSUE TITLE
Canvas REPL <Run>

### ISSUE THREAD

**Issue by AlGuise** [learn-co-curriculum/phase-0-pac-1-logical-operators#6] opened 2022-02-02 23:17 UTC
### Canvas Link

https://learning.flatironschool.com/courses/5461/pages/logical-operators?module_item_id=353239

### Concern

When clicking the <Run> button as instructed on the page nothing happens. Similar if I open REPL it still doesn't run. It appears as though there is a console.log() action missing. I have figured a work around but it was not clear and I had to reach out to support for the solution. I think this could be made a little clearer in the instructions if it is already in there somewhere or fixed so that examples actually work.

### Additional Context

![Before](https://user-images.githubusercontent.com/98363807/152253071-bfa91bab-4afc-46cb-80e1-b5635140d1df.png)
![After](https://user-images.githubusercontent.com/98363807/152253087-d856452f-3bae-40bb-bf9a-fe0971ed052b.png)

### Suggested Changes

Add needed code for the code to actually give an output in console.
Specify what code needs to be added on and where for students to get practice.

**Comment by lizbur10** [comment] 2022-02-03 15:18
Hi @AlGuise ! Thanks for bringing this to our attention.

We are aware of the problem and are working on a fix, but it will likely take a bit of time to resolve. In the meantime, as a workaround, you can continue wrapping code in a `console.log` as you've been doing, or you can type or copy/paste code directly into the console window and press enter.

Apologies for the inconvenience! The problem is due to a change that was made by repl.it, so it is out of our control. We are currently working on updating the affected lessons to use a different approach.

Thanks for contributing to the Flatiron School curriculum! 💙

**Comment by lizbur10** [comment] 2022-02-22 15:08
Hi @AlGuise ! The updates to the prework lessons and labs in response to this change have been completed. Note that, depending on when you were assigned to a prework course, the changes may not be reflected in your Canvas lessons. Our apologies for any inconvenience this causes you. 

Thanks again for contributing 💙

**Closed as completed by lizbur10** 2022-02-22 15:08 UTC
Labels: se curriculum
